### ISSUE TITLE
Suggestion: Consider Renaming Your Blog Post Week Numbers

### ISSUE THREAD

**Issue by ishana-goyal** [ossd-s23/gracezhang89-weekly#1]
Hi Grace!

I noticed that since spring break your blog post week numbers no longer align with the week structure on the course website. For example, I believe your current Week 8 post on group work updates / Jim Hall thoughts should actually be called Week 9 (since Week 8 is Spring Break and can be skipped). Likewise, your latest post lines up with Week 10, not Week 9. This is probably not a huge deal, just wanted to flag it to you!

**Comment by gracezhang89** [comment]
Thanks Ishana, will fix that!
